POST http://localhost:3000/localhost:3000/restaurants/
Content-Type: application/json

{
"name":"Test Restaurant with Post",
"phone":"17656972344",
"website":"tastethetropics.com",
"city_id":2,
"picture":"https://ik.imagekit.io/bwcdq46tkc8/mini-yelp/tasteOfTropics-restaurant_x1QbKwyjJN.jfif?updatedAt=1631309125693","created_at":"2021-09-09T18:33:20.000Z"
}